name: simple_media_picker
description: A Flutter plugin for easy media picking with album browsing, multi-selection support, and lazy loading.
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  photo_manager: ^3.6.4
  photo_manager_image_provider: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0